# Base configs
# baseurl: "https://photography.rampatra.com"
baseurl: "https://santiagocruzb.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Fotografía por Santiago Cruz"
subtitle: "See the world through my eyes!"
author: "Santiago Cruz"
header:
 title: "Photography"
 subtitle: "by Santiago Cruz"
footer:
 name: "Hola"
 bio: "Raco es mi pastor, nada me ha de pasar"
#  github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "SC"
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  # twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/santiagocruzph"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  # github: "https://www.github.com/rampatra"
