# Base configs
# baseurl: "http//localhost"
# baseurl: "https://santiagocruzb.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-HVHBT12QNE"

# UI configs
title: "Photography by Santiago Cruz"
# subtitle: "See the world through my eyes!"
author: "Santiago Cruz"
header:
 title: "Photography"
 subtitle: "by Santiago Cruz"
footer:
#  name: ""
 bio: "Self-taught photographer plus 7 years of experience. Landscape, astrophotography, sports and 35mm format. I have a dog."
 mail: "Contact me at santiago [dot] cruz [dot] barrenechea [at] gmail [dot] com"
#  github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
# web_design: "SC"
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  # twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/santiagocruzph"
  photopx: "https://www.500px.com/santiagocruzb"
  youtube: "https://www.youtube.com/santiagocruzb"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  # github: "https://www.github.com/rampatra"
